### ISSUE TITLE
方針について

### ISSUE THREAD

**Issue by tacigar** [minetest-jp/yamato-modpack#1]
inviteありがとうございました。
それで、いきなりで申し訳ないのですが、このmodpackはどのように開発を進めていく予定なのでしょうか？

**Comment by ghost** [comment]
ローリングリリース方式として、和風なアイテム・ノードを随時追加していく形で進めます。
また、前回の和風Modの要素の一部は再利用します。
バージョン番号はありません。
実装予定の要素の一覧は後日projectsとして出します。

また、開発にあたって大まかなルールをまとめてみましたが、Modの分け方をどうすべきか迷っています。

## 案1: 要素を単体のModとして分ける

畳なら畳、布団なら布団のModとして分ける。
これはこのModの依頼主、REO氏のアイデアに基づくものです。
(しかし彼はMinetestをやめています)

> 例:
> japan_futon
> japan_tatami

### メリット
- ユーザーが欲しい機能を取捨選択できる。
- 管理・開発が比較的楽。

### デメリット
- ユーザーがModを選択する場合、依存関係が面倒。

依存を小さくすることである程度軽減できる。
- Modの一覧を埋めてしまう。

`/mods`の出力がかなり増える。
- ゲーム開始までが長くなる・重くなる可能性がある。

推測。

## 案2: 要素をある程度グループ分けする

畳や布団などの装飾系、稲や茶などの農業系…のように分ける。
こちらの方が一般的。

> 例:
> japan_decor
> japan_farming

### メリット
- 案1のデメリットをほぼカバーしている。
- 一般的な方式なので、ユーザーが理解しやすい。

### デメリット
- グループが曖昧なアイテム・ノードはどのModに入れるべきか考える必要がある。

明示的なグループ分けの方法が必要。
- 同Mod内でのファイル管理が面倒。

intllib用テキストの中身や、テクスチャが多くなる。
- 案1に比べ、要素を選択できない。

同Modpack内で依存しているModがあると、さらに選択の余地が狭まる。

以下、大体決まったもの

---

## Mod名

頭に`japan_`を付ける。

> 例: japan_trees

## テクスチャ名

頭に`japan_`を付ける。

> 例: japan_tatami.png

## アイテム・ノード名

`japan:*`の形式。

## アイテム・ノードのdescription

名詞はヘボン式ローマ字。
修飾語は英語。
intllibで翻訳出来るようにする。

> 例: Half tatami

## レシピ

なるべくMTGのアイテムだけでクラフトできるようにする。

## depends.txt

上から
- 依存Mod
- 依存Mod (任意)
- MTGのMod

の順で記述する。

> 例:
> japan_trees <- 依存
> intllib? <- 任意
> default <- MTG
> wool

## mod.conf

Mod名を記述する。

> 例:
> name = japan_trees

## license.txt

Modフォルダの配下に置く。
ライセンスはコードやテクスチャの作成者が指定する。

ライセンスの中身は以下のようにする。

### textureやsoundsなどを含まない場合

```
(ライセンス名)

Copyright (c) 2016 製作者名

(ライセンス文)
```

### texturesやsoundsを含む場合

```
License of source code
----------------------

(ライセンス名)

Copyright (c) 2016 製作者名

(ライセンス文)


License of textures
-------------------

(ライセンス名)

Copyright (C) 2016 製作者名

(ライセンス文)
```

Mod内でライセンスが複数の場合は、ライセンス文を省略し、以下の書式で書く。

```
(ファイル名) - (ライセンス名) - (製作者名)
```

## ファイルの文字コード

Unicode (UTF-8)。

## コード内のコメント

書いても書かなくてもよい。
また、日本語でも英語でもよい。
個人の裁量に任せることにする。

## intllib

``` lua
-- intllib funtion
local S = (function()
    if minetest.get_modpath("intllib") then
        return intllib.Getter()
    end

    return (function(str)
        return str
    end)
end)()
```

**Comment by ghost** [comment]
前回のものから一部のファイルを引き継ぐにあたって、元々DuroomZaccさんのものとして作られたファイルは、tacigarさんのものとして表記すべきでしょうか？
同じ方でしたよね…？

**Comment by ghost** [comment]
もう一つ。
minetest-jpのorganizationを開かれたようですので、このリポジトリをそちらに移動しようと思うのですがどうでしょうか。

**Comment by tacigar** [comment]
方針の件大体把握しました。
個人的には案２が自然かなぁとは思います。

いや、別人です（ということで…笑）
ので、DuroomZacc表記のままでいいんじゃないでしょうか？
というか表記消してもいいんじゃ…笑

**Comment by tacigar** [comment]
> minetest-jpのorganizationを開かれたようですので、このリポジトリをそちらに移動しようと思うのですがどうでしょうか。

いいっすね！ :)

その前に、少し…。
僕の個人的な感覚なんですが、Japan MODというのは少し直球すぎるような気がしていて…。
すでに前の和風MODの名前をjapanなにがしに変えてしまっているのであればそれでいいのですが、もしまだ何も手をつけていないのであれば、何か一緒に考えませんか？

**Comment by ghost** [comment]
分かりました。

表記と言うのはライセンスに製作者名として書くということです、説明不足でした。
では、DuroomZaccさんとして表記することにしますね。

DuroomさんのテクスチャのライセンスはCC BY-SA 4.0ということでよろしいでしょうか？
本人ではないと言っている方に尋ねるのもどうかと思いますが(笑)

> 僕の個人的な感覚なんですが、Japan MODというのは少し直球すぎるような気がしていて…。
> すでに前の和風MODの名前をjapanなにがしに変えてしまっているのであればそれでいいのですが、もしまだ何も手をつけていないのであれば、何か一緒に考えませんか？

良いですね、了解しました。
手をつけていないと言えば嘘になりますが、十分変更できる範囲なので、決まったら変更しますね。

**Comment by ghost** [comment]
大和Mod、なんてどうでしょうか？
ローマ字にするとあまり映えませんが…

**Comment by tacigar** [comment]
あ〜。
Japanese Modpackを見てみたんですが、DuroomZaccが作ったものって、ほとんどないですね…。
ほとんどRuiさんのものみたいなので、DuroomZaccが作成したものもライセンス表記はざっくりRuiさんオンリーにしてくださって構わない（と思っているはず）ですよ。

> 良いですね、了解しました。
> 手をつけていないと言えば嘘になりますが、十分変更できる範囲なので、決まったら変更しますね。

すいません。
わがままを申しまして…。m(__)m

**Comment by ghost** [comment]
了解しました。

いえいえ、名前は大事です、私がそれを軽視しすぎたのです。

**Comment by tacigar** [comment]
> 大和Mod、なんてどうでしょうか？

いいですね。
`yamato`。
字の並びの雰囲気も悪くないです。

ジパング `zipangu` (長いので個人的には `zipang`の方がしっくりくる)の響きも結構好きかもです…。

**Comment by ghost** [comment]
ジパング、良いですね！
以前、そんな名前のリポジトリを立てられていたような…？

**Comment by tacigar** [comment]
> いえいえ、名前は大事です、私がそれを軽視しすぎたのです。

いやいや、`japan`ももちろん良いと思うのですが、これから作っていくにあたって、MinetestのForumなどに投稿することもありうると思い、その際に「日本」と題したMODを出すのはちょっとプレッシャーだなぁと思いまして…。

**Comment by ghost** [comment]
> 「日本」と題したMODを出すのはちょっとプレッシャーだなぁと思いまして…。

確かに…

日本以外のユーザーにとっては、ジパングの方が通じやすそうなので、Modpack名はジパングでいきましょうか。

**Comment by tacigar** [comment]
> ジパング、良いですね！

`zipang`だと収まりはいいのですが、`zipangu`だと文字の並びがすごく格好悪いと感じます。
正式には`zipangu`なので、どうしたものかなぁといった感じです。

> 以前、そんな名前のリポジトリを立てられていたような…？

僕も見たことあるような、ないような…笑

**Comment by tacigar** [comment]
> 日本以外のユーザーにとって、ジパングの方が通じやすそうなので、そちらでいきましょうか。

ジパングというと「黄金の国」というイメージがありまして、そういうMODなのかなと思われてしまうんじゃないかなと思ってしまうのと、`zipangu`という名前が長くて格好わるいのと、かといって`zipang`だと都合よく名前変えてる感があるのと、などなど色々考え始めると、大和の方が良いと感じてきました。

**Comment by ghost** [comment]
大和って英語でも通じるかな、と思って調べたらJapaneseと訳されるようでした。
Forumで公開するなら訳注を付けるべきでしょうが、これでは結局Japanとそう変わらない…。

どうあがいてもハードルが高くなりますね…。

**Comment by tacigar** [comment]
> 大和って英語でも通じるかな、と思って調べたらJapaneseと訳されるようでした。

う〜む。
`zipang`はweblioで調べると、「かわぐちかいじによる日本の漫画作品。」と出てきました。

「桜」、「雅」、「神楽」、「花鳥風月」など日本そのものとは違うけど、日本っぽい単語から探してみます？

**Comment by ghost** [comment]
そうですね。
桜とかだと、それに応じた要素を加えなければならなくなったり、それだけのModという感じになってしまう気がしますね。

**Comment by tacigar** [comment]
たしかに…。
マインクラフトの竹MOD？も竹が中心になっていたような覚えがあります。
そうするとMODとしての幅を狭めてしまう気もしましますよね…。

**Comment by ghost** [comment]
例として挙げられている「雅」とか良いと思います。
概念ならModの幅を制限することは無さそうですし。

**Comment by tacigar** [comment]
なるほど…。
`miyabi`…。
`yamato`…。
`miyabi_farming`…。
`yamato_farming`…。

やっぱり`yamato`のほうがいいような気が…。
`yamato`がJapaneseという意味としても、直接`Japan`というのとは結構受ける感覚が違うと思うし、全然ありな気がします…。

**Comment by ghost** [comment]
確かに直接的なイメージはありませんね。
では、大和Modということでいきましょうか。

**Comment by tacigar** [comment]
そうしましょう！＼(^o^)／

**Comment by ghost** [comment]
名前の変更とリポジトリの移動を行いました。

**Comment by tacigar** [comment]
お、確認しました。

本当細かくて申し訳ないのですが、`yamato_modpack`じゃなく、`yamato-modpack`にしませんか？

**Comment by ghost** [comment]
変更しました。
そういえば、Modpackならハイフンが使えましたね。

**Comment by tacigar** [comment]
すいませんm(__)m
ありがとうございます。

**Comment by ghost** [comment]
今からmodpack.txtを追加するだけの、first commitを行おうと思うのですが、コミットの規約も作っておいた方が良いでしょうか？
コミットの種別を表記するだとか、日本語でも良いだとか…

**Comment by tacigar** [comment]
ぶっちゃけあまりGitに慣れていないので、そういった規約を作っていただいたほうが粗相はしないかもしれません…。

**Comment by ghost** [comment]
では、コミットの規約は以下の通りで。
- コミットメッセージは英語
- コミットメッセージ2行目以降での説明はあってもなくてもよい
- 書式は`[種別] 概要`とする

種別: Add, Remove, Fix, Update

> 例: [Add] Add modpack.txt

ここまで書いておいて何ですが、自分でも守りきれるかわかりません…。

**Comment by ghost** [comment]
modpack.txtを作成しました。

**Comment by ghost** [comment]
追記: 実装予定の要素の一覧は、リポジトリのProjectsの方に書くことにします。

**Comment by tacigar** [comment]
コミット規約了解いたしました！

modpack.txt了解です。

よろしくお願いいたします！
実装予定の要素は自分も書いてもいいんでしょうか？

**Comment by ghost** [comment]
改めてよろしくお願いいたします。

大丈夫です。
予定でなくとも、実装したいものなどを書いていただいても結構です。

**Comment by tacigar** [comment]
了解です！

**Comment by tacigar** [comment]
こちらこそよろしくお願いいたします！

**Comment by ghost** [comment]
開発規約は別issueに移したので、このissueは閉じますね。
