### ISSUE TITLE
開発規約について

### ISSUE THREAD

**Issue by tacigar** [minetest-jp/yamato-modpack#12]
> Forkしたリポジトリからプルリクエストを送信してください。
> メインリポジトリにブランチを作ることや、直接コミットすることは禁止します。

GitHub の Fork の意味がいまだによく分かっていなくて...
オープンソースなプロジェクトで, 誰も彼もにマインリポジトリにブランチを作られてしまうとややこしいという理由で, こういった規約があるんでしょうか.

定数にしたい変数はそれと分かるように大文字のスネークケースで書くのが好きです.
`local TUU_KAA = 30` と書かれていれば `TUU_KAA` は変更しちゃいけないんだなと分かるので.

引数のカッコの省略の禁止は何故でしょうか.

**Comment by Rui-Minetest** [comment]
開発規約ですが、若干制限しすぎた感があるので色々緩和するつもりです。
メインリポジトリへのブランチ作成は許可にしようと思います。(直接コミットは禁止です)

> 定数にしたい変数はそれと分かるように大文字のスネークケースで書くのが好きです.

定数のことについて書くのを忘れていました…。その書き方で大丈夫です。

> 引数のカッコの省略の禁止は何故でしょうか.

この制限も無くすつもりです。関数呼び出しの記法に一貫性を持たせたかったというだけなのですが、読みにくくなることもなさそうですので撤廃します。

**Comment by Rui-Minetest** [comment]
開発規約の簡略化を行いました。
